#51 Refactor score logic outside the Vue app
skontar/cvss-v4.0-calculator pull request #52
Opened 2024-03-09 03:30 UTC by gscottwilson

Hello, I work with Chris Turner and our team would like to use your calculator scoring logic for V4 scoring. 
In the PR you'll see I've moved the scoring logic outside of the Vue app methods section in order to make it more easily available for 3rd party use (when a full web application is not required). This works for us.

I've attempted to leave the structure of the Vue app the same with no build steps introduced and minimal refactoring. 

I've done limited testing comparing several different vector selections to the production V4 calculator and am seeing matching scores and no error messages.

2024-03-12 10:29 UTC, skontar approved these changes

2024-03-12 11:28 UTC, jsvob approved these changes

2024-03-12 11:37 UTC, skontar commented
I think we should also change [line 172 in index.html](https://github.com/RedHatProductSecurity/cvss-v4-calculator/blob/main/index.html#L172) to force loading new app.js version and not the cached one on some browsers.

2024-03-12 11:38 UTC, skontar requested changes
I think we should also change [line 172 in index.html](https://github.com/RedHatProductSecurity/cvss-v4-calculator/blob/main/index.html#L172) to force loading new app.js version and not the cached one on some browsers.

2024-03-12 21:00 UTC, gscottwilson commented
> I think we should also change [line 172 in index.html](https://github.com/RedHatProductSecurity/cvss-v4-calculator/blob/main/index.html#L172) to force loading new app.js version and not the cached one on some browsers.

Good catch! done

2024-03-13 08:52 UTC, skontar approved these changes

2024-03-13 08:52 UTC, merged