Solving issue #33 and refreshing the README
skontar/cvss-v4.0-calculator pull request #62
Opened 2024-08-30 16:14 UTC by n3rada

Now than we have a class-based approach and because I am now quite familiar with the code, I can propose this modification in order to solve #33:

![image](https://github.com/user-attachments/assets/59feeee9-c583-4d38-8885-2f699d984d3b)

2024-09-03 09:11 UTC, n3rada commented
That way, after this merge, we'll be in complete harmony with [FIRST](https://github.com/RedHatProductSecurity/cvss-v4-calculator/compare/main...FIRSTdotorg:cvss-v4-calculator:main), and they'll be able to synchronize their projects and rely on RedHat's quality.

2024-09-03 10:43 UTC, pandatix commented
Commit message "Adapting to FISRT commits" has a typo, should be FIRST :)

2024-09-04 09:48 UTC, n3rada commented
Typo fixed!

2024-09-04 14:37 UTC, superbuggy requested changes

2024-09-04 14:37 UTC, superbuggy commented on cvss40.js
> +        const twoValueMacrovectors = [1, 5]; // Indices for macrovectors 2 and 6 (0-based index)
It would be better to obtain these indexes using `.indexOf`/`.findIndex` rather than using magic numbers.

2024-09-04 20:07 UTC, n3rada commented on cvss40.js
> +        const twoValueMacrovectors = [1, 5]; // Indices for macrovectors 2 and 6 (0-based index)
Very good point. I've modified it, trying to think a little more modular than my original proposal. Does that work for you @superbuggy?

2024-09-05 19:21 UTC, superbuggy commented on cvss40.js
> +        const twoValueMacrovectors = [1, 5]; // Indices for macrovectors 2 and 6 (0-based index)
```js
const macroVectorDetails = {
            "Exploitability": 0,
            "Complexity": 1,
            "Vulnerable system": 2,
            "Subsequent system": 3,
            "Exploitation": 4,
            "Security requirements": 5
        };
    
        // Lookup table for macrovectors with three possible values
        const macroVectorValuesThreeOptions = [ "High", "Medium", "Low" ];
    
        // Lookup table for macrovectors with two possible values
        const macroVectorValuesTwoOptions = [ "High", "Low" ]
    
        // Define which macrovectors have two values
        const twoValueMacroVectors = ["Complexity", "Security requirements"]; 
    
        // Construct the detailed breakdown
        return Object.fromEntries(
            Object.entries(macroVectorDetails).map(([description, index]) => {
                const currentValue = macroVector[index];
                // Use the appropriate lookup table based on the macrovector
                const macroVectorValueOptions = twoValueMacroVectors.includes(description)
                    ? macroVectorValuesThreeOptions
                    : macroVectorValuesTwoOptions;
                return [
                    description,
                    macroVectorValueOptions[currentValue]
                ];
            })
        );
```

2024-09-05 19:23 UTC, superbuggy requested changes
The code could be simplified and less dependent on hard-coded values or magic numbers.

2024-09-05 19:43 UTC, superbuggy commented on cvss40.js
> +        const twoValueMacrovectors = [1, 5]; // Indices for macrovectors 2 and 6 (0-based index)
I'm not sure there's a reason for `macroVectorDetails`  to be a an object, it seems it could just be an array. Maybe something like...

```js
const macroVectorDetails = [
            "Exploitability",
            "Complexity",
            "Vulnerable system",
            "Subsequent system",
            "Exploitation",
            "Security requirements",
        ]
    
        // Lookup table for macrovectors with three possible values
        const threeSeverities = [ "High", "Medium", "Low" ];
    
        // Lookup table for macrovectors with two possible values
        const twoSeverities = [ "High", "Low" ]
    
        // Define which macrovectors have two values
        const macroVectorsWithTwoSeverities = ["Complexity", "Security requirements"]; 
    
        // Construct the detailed breakdown
        return Object.fromEntries(
            macroVectorDetails.map((description, index) => {
                // Use the appropriate lookup table based on the macrovector
                const macroVectorValueOptions = macroVectorsWithTwoSeverities.includes(description)
                    ? threeSeverities
                    : twoSeverities;
                const indexOfOption = macroVector[index];
                return [ description, macroVectorValueOptions[indexOfOption] ];
            })
        );
```

This is probably a little easier to reason about (if it does work correctly).

2024-09-06 07:57 UTC, n3rada commented on cvss40.js
> +        const twoValueMacrovectors = [1, 5]; // Indices for macrovectors 2 and 6 (0-based index)
But, this proposal is clearly quite similar to my first code isn't?

2024-09-06 08:02 UTC, n3rada commented on cvss40.js
> +        const twoValueMacrovectors = [1, 5]; // Indices for macrovectors 2 and 6 (0-based index)
With this kind of code, the code still has some dependencies on hard-coded values (magic numbers) due to the reliance on fixed severity levels for macrovectors and their descriptions.

2024-09-06 08:08 UTC, n3rada commented
In my opinion, the `severityBreakdown` method is the only place where these values (like the severity levels or macrovector descriptions) are used, then you don't really need to over-engineer the solution. In that case, having some level of hard-coding within the function seem really acceptable.

I am a little out of other ideas for this method. It works, it is great. Let's merge! 😇

2024-09-06 08:20 UTC, merged

2024-09-06 08:46 UTC, n3rada commented
Thank you, @skontar. I’m quite disappointed that FIRST doesn’t allow pull requests to their repository for merging upstream. It feels somewhat unprofessional.

2024-09-06 10:05 UTC, skontar commented
@n3rada no worries, this is the master development repository. They fork it from time to time to deploy on their site. If some updates were not ported back, it is likely oversight, not intent.

2024-09-06 10:05 UTC, skontar commented
We are upstream, BTW.

2024-09-06 11:53 UTC, superbuggy commented
> In my opinion, the `severityBreakdown` method is the only place where these values (like the severity levels or macrovector descriptions) are used, then you don't really need to over-engineer the solution. In that case, having some level of hard-coding within the function seem really acceptable.
> 
> I am a little out of other ideas for this method. It works, it is great. Let's merge! 😇

With our implementation, some level of hardcoding is inevitable however with the changes you made, it minimizes the amount of hard-coded values, which is desirable. Thank you again!

2024-09-06 13:04 UTC, n3rada commented
So, will any changes made here eventually be reflected on the FIRST website? I know that penetration testers relies on your site in our reports. It seems more legit to the community.

2024-09-06 14:22 UTC, skontar commented
@n3rada yes, eventually, it should be reflected there.